version: 2
jobs:
  build:
    working_directory: ~/react-native-sample
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - restore_cache:
          name: Restore Node Modules Cache
          key: node-v1-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          name: Save Node Modules Cache
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Unit Test
          command: |
            mkdir -p test-results/jest
            yarn run test:ci
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - persist_to_workspace:
          root: ~/react-native-sample
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
